---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
  roles:
    - deploy
<<<<<<< HEAD
    - configure-prometheus-node-exporter
=======
    
>>>>>>> 8a98492177e1bda95ea6ae2d4f29884881e1b3aa
