---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  - name: "clean up server"
  become: true
  shell: "sudo rm -rf *"
- name: "git clone repo"
  become: true
  shell: "git clone https://github.com/Nyeve/UdaPeople_Autodeploy_App.git"
- name: "install dependency"
  become: true
  shell: "sudo npm install"
  args:
    chdir: "/home/ubuntu/UdaPeople_Autodeploy_App/backend"
- name: "install peers dependency"
  become: true
  shell: "sudo npm install -g npm-install-peers"
  args:
    chdir: "/home/ubuntu/UdaPeople_Autodeploy_App/backend"
- name: "build backend server"
  become: true
  shell: "npm run build"
  args:
    chdir: "/home/ubuntu/UdaPeople_Autodeploy_App/backend"
- name: "run backend server"
  become: true
  shell: "pm2 start npm --name 'udapeople' -- start"
  args:
    chdir: "/home/ubuntu/UdaPeople_Autodeploy_App/backend"
  async: 45
  poll: 0
  roles:
    - deploy
